name: Unmute
options:
  bundleIdPrefix: com.unmute
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true
  groupSortPosition: none

settings:
  base:
    SWIFT_VERSION: "5.0"
    INFOPLIST_FILE: Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.unmute.alarmapp
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    PRODUCT_NAME: Unmute
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    GENERATE_INFOPLIST_FILE: false
    INFOPLIST_KEY_CFBundleDisplayName: UNMUTE
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    SWIFT_EMIT_LOC_STRINGS: "YES"
    ENABLE_PREVIEWS: "YES"
    CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"

targets:
  Unmute:
    type: application
    platform: iOS
    sources:
      - path: UnmuteApp.swift
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
      - path: Utilities
        optional: true
      - path: Resources
        buildPhase: resources
        optional: true
      - path: Assets.xcassets
        buildPhase: resources
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false
    entitlements:
      path: Unmute.entitlements
    dependencies:
      - sdk: AlarmKit.framework
        weak: true
      - target: UnmuteWidgetExtension
        embed: true
        codeSign: true
        embedType: appExtension

  UnmuteWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: UnmuteWidgetExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.unmute.alarmapp.widget
        PRODUCT_NAME: UnmuteWidgetExtension
        PRODUCT_MODULE_NAME: UnmuteWidgetExtension
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false
        INFOPLIST_FILE: UnmuteWidgetExtension/Info.plist
        GENERATE_INFOPLIST_FILE: false
        SWIFT_VERSION: "5.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../../Frameworks @executable_path/../Frameworks"
    entitlements:
      path: UnmuteWidgetExtension/UnmuteWidget.entitlements
    dependencies:
      - sdk: AlarmKit.framework
        weak: true
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
